services:
  postgres:
    image: postgres:16-alpine
    container_name: estoque_os_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estoque_os_dev
    ports:
      - "5433:5432"
    volumes:
      - estoque_os_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  estoque_os_pgdata:
